### ISSUE TITLE
ClojureDart `#/` parametrized type support

### ISSUE THREAD

**Issue by NoahTheDuke** [borkdude/edamame#102]
**Is your feature request related to a problem? Please describe.**
ClojureDart has a small reader dispatch extension, `/`, which adds support for [parametrized types](https://github.com/Tensegritics/ClojureDart/blob/main/doc/differences.md#parametrized-types). It's implemented with a data reader ([source](https://github.com/Tensegritics/ClojureDart/blob/a8b114ed8f8d469129a882bf87828d79e338c05c/clj/src/cljd/compiler.cljc#L4129)).

The data reader provides support in two different ways:
* the base is `#/[List int]` is transformed to `^{:type-params [int]} List`. It's like the meta reader, and it works recursively.
* There's also support for functions with `->`: `#/(int -> Null)` is transformed to `^{:params-types [Null int] :type-params nil} dart:core/Function`.

```clojure
(dart-type-params-reader '[List])
; List
(dart-type-params-reader '[List [List int]])
; ^{:type-params (^{:type-params (int)} List)} List
(dart-type-params-reader '( int -> Never))
; ^{:params-types (Never), :type-params nil} dart:core/Function
(dart-type-params-reader '(dynamic -> [List int]))
; ^{:params-types (^{:type-params (int)} List dynamic), :type-params nil} dart:core/Function
```

**Describe the solution you'd like**
Edamame can read ClojureDart files without throwing an exception.

**Describe alternatives you've considered**
Fork edamame to add support, do nothing.

**Additional context**
I think that supporting a subset of this is a pretty simple extension and have a working branch that does so. I'm willing to open a PR with the change if so desired.

My subset would be the `:type-params` version, and leave off the function-specific parsing. `#/(-> List)` would be rendered as `->` with metadata `{:type-params [List]}`.

**Comment by borkdude** [comment]
You can provide data readers like so:

```
user=> (e/parse-string "#/[List int]" {:readers {'/ identity}})
[List int]
```

Edamame supports JVM Clojure and ClojureScript, but other dialects can be supported through these options.

**Comment by NoahTheDuke** [comment]
That's interesting about CLJS. What features aren't supported in JVM Edamame?

Would you accept a pr for adding documentation to the readme about adding this support?
