### ISSUE TITLE
Edamame not keeping previous metadata for functions

### ISSUE THREAD

**Issue by AlexAti** [borkdude/edamame#114]
**version**

edamame 1.4.24

**platform**

MacOS Sonoma 14.6.1
Clojure 1.12.0.1479

**problem**

Sorry if this is expected behaviour, but I could not see it mentioned in the docs (closest doc is about the postprocess, but both the input function and the output collection should be able to keep the metadata).

When reading a file with metadata on a function, the resulting collection that represents the function does not keep the metadata.

**repro**

This is a file that reproduces the issue: 

```
(ns test.test
  (:require [edamame.core :as e]))

(def source-file (slurp "src/test/test.clj"))

(defn ^{:test "yes!"} hello-world [] "hey")

(def parsed-file
  (e/parse-string-all source-file))

(println "Targeted collection is:" (nth parsed-file 2))
(println "Does its meta contain :test?:" (:test (meta (nth parsed-file 2))) "...")
```
**expected behavior**

I expected the :test kv pair to be kept as the code does vary-meta on the function metadata.

**Comment by borkdude** [comment]
`(nth parsed-file 2)` returns the expression `(defn ^{:test "yes!"} hello-world [] "hey")` but the metadata is on the symbol `hello-world`:

```
(println "Does its meta contain :test?:" (:test (meta (second (nth parsed-file 2)))) "...")
```

```
Does its meta contain :test?: yes! ...
```
