### ISSUE TITLE
packaging edamame for npm

### ISSUE THREAD

**Issue by zcaudate** [borkdude/edamame#49]
Would it be possible to push a version of edamame as a js library to npm?

That way non-cljs codebases can have access to it. It's a really awesome library and I'm really surprised that `read-string` in clojure doesn't actually do that. It saved me a lot of time debugging config files.

**Comment by borkdude** [comment]
@zcaudate edamame returns clojure data structures. what would you do with them in JS?

**Comment by zcaudate** [comment]
It's pretty useful for fragments of `:edn` that gets sent through http or ws.

there is precedence for this: https://robert.kra.hn/past-projects/paredit-js.html

**Comment by borkdude** [comment]
The example you link to is somewhat different from what edamame does. Edamame does not preserve whitespace. It saves locations as metadata on s-expressions, that are not necessarily representable in EDN/JSON.
Something like https://github.com/carocad/parcera comes closer to the example you linked to.

Having said this, nothing stops you from transforming the s-expressions + metadata into EDN/JSON structures and then expose that as a JS library, but that's not part of this library.

**Comment by borkdude** [comment]
One alternative is to use sci to parse EDN/Clojure. Sci is available on NPM.

https://github.com/borkdude/sci

**Comment by zcaudate** [comment]
Oh. that's actually better. Thanks!
