### ISSUE TITLE
support reading symbols with two slashes in them

### ISSUE THREAD

**Issue by mk** [borkdude/edamame#92]
**version**

1.0.0

**platform**

macOS

**problem**

I would like to be able to read symbols with two slashes in them using edamame.

**repro**

```clojure
(require '[edamame.core :as edamama]
         '[clojure.edn :as edn])

(edn/read-string "foo/bar/baz")
;; => foo/bar/baz

(read-string "foo/bar/baz")
;; => foo/bar/baz

(edamame.core/parse-string "foo/bar/baz" {})
;; throws clojure.lang.ExceptionInfo Invalid symbol: foo/bar/baz.
```
**expected behavior**

Match the behaviour of `clojure.core/read-string` & `clojure.edn/read-string`.

**Comment by borkdude** [comment]
>  '/' has special meaning, it can be used once in the middle of a symbol to separate the namespace from the name

https://clojure.org/reference/reader#_symbols

Although clojure itself accepts this, it only does this because it doesn't check its own spec (see above). Tools.reader on the other hand does not accept that and edamame and e.g. ClojureScript's reader use that.

```
$ plk
ClojureScript 1.10.914
cljs.user=> 'foo/bar/baz
Syntax error reading source at (<cljs repl>:1).
Invalid symbol: foo/bar/baz.
```

**Comment by borkdude** [comment]
Edamame uses tools.reader for reading symbols, etc:

```
 $ clj
Clojure 1.11.0
user=> (require '[clojure.tools.reader :as r])
nil
user=> (r/read-string "foo/bar/baz")
Execution error (ExceptionInfo) at clojure.tools.reader.impl.errors/throw-ex (errors.clj:34).
Invalid symbol: foo/bar/baz.
```

If you can convince the core people to change this behavior, it will be automatically supported in edamame, but I'm not comfortable making edamame more accepting in things that are against the spec.
