### ISSUE TITLE
Data readers for comments and #_ discard next form

### ISSUE THREAD

**Issue by NoahTheDuke** [borkdude/edamame#94]
**Is your feature request related to a problem? Please describe.**
I am using edamame to analyze clojure code. I would like to be able to analyze `;` comments and the `#_` discard next form reader macros.

**Describe the solution you'd like**
A flag in parse that converts comments and #_ to some sort of edamame tagged literal, maybe converting `; hello, I'm a comment` to `#edamame/comment "hello, I'm a comment"` and `#_ (println sym)` to `#edamame/discard (println sym)`. I'm not sure exactly what's possible, but this would help me a lot.

**Describe alternatives you've considered**
I could switch to a different parsing engine, like rewrite-clj. That's slower but the library is more featureful.

**Comment by borkdude** [comment]
@NoahTheDuke This can result into invalid reads, like:

```
{:a 1 #_2}
```

**Comment by borkdude** [comment]
I think at this point you're better off using rewrite-clj directly since edamame doesn't concern itself with whitespace (or elements like `#_` which are usually dropped), given the problem above.

**Comment by NoahTheDuke** [comment]
Sure, that makes sense. Thanks.
